version: 'latest'
services:
  web:
    image: smile-server:latest
    ports:
      - "8888:8888"
    volumes:
      #- "/Users/chc/gits/SMILE_app/server/app:/app"
      - "C:/gits/SMILE_server/app:/app"
